#!/usr/bin/python
import sys
from matrix import multimatrix, itermatrix, random_m, iterate_results
import matrix
import timeit


if __name__ == '__main__':

    """parameter is like:
    file name of matrix A
    file name of matrix B
    number of processes used
    """

    number_of_cpu = int(sys.argv[-1])
    from matrix import multimatrix, read_matrix
    a = read_matrix(sys.argv[1])
    b = read_matrix(sys.argv[2])
    p = multimatrix(a, number_of_cpu) * multimatrix(b, number_of_cpu)
