#!/usr/bin/python
import sys
from matrix import multimatrix, itermatrix, random_m, iterate_results
import matrix
import timeit


if __name__ == '__main__':
    '''a = [[1, 3], [-5, 6], [2, 4]]
    b = [[1, 4], [8, 7]]
    adotb = [[25, 25], [43, 22], [34, 36]]
    A = multimatrix(a)
    B = multimatrix(b)
    prod = A * B
    assert(adotb == prod)
    print prod, "multi test OK"
    A = itermatrix(a)
    B = itermatrix(b)
    iterprod = A * B
    listprod = iterate_results(iterprod)
    assert(adotb == listprod)
    print listprod, "iter test OK" '''
    size_of_matrix = int(sys.argv[1])
    number_of_cpu = int(sys.argv[-1])
    from matrix import multimatrix, random_m, iterate_results
    a = random_m(size_of_matrix, size_of_matrix)
    p = multimatrix(a, number_of_cpu) * multimatrix(a, number_of_cpu)
